MH_TitleID = "ID"
MH_TitleTexture="Texture"
MH_PRESETS = "Presets"

MH_Player = "Player"
MH_Target = "Target"
MH_Party1 = "Party" .. "1"
MH_Party2 = "Party" .. "2"
MH_Party3 = "Party" .. "3"
MH_Party4 = "Party" .. "4"
MH_TitleName = "Model"
MH_TITLEMANUALID = "Manual ID Entry:"
MH_ADDPRESETS = "+"
MH_DELETEPRESET = "-"

MH_TOOLTIPMORPH = "Click to morph %s"
MH_TOOLTIPMORPHMOUNT = "Click to morph %s's mount"
MH_TOOLTIPMORPHRESET = "Click to reset %s's morphs\nRelogging will clear morphs if this fails"
MH_TOOLTIPMORPHINFO = "Click to see %s's displayID"
MH_TOOLTIPMOUNTINFO = "Click to see %s's mount displayID"
MH_TOOLTIPMOUNTRESET = "Click to reset %s's mount morphs\nRelogging will clear morphs if this fails"
MH_TOOLTIPNOUNIT = "Unit not found"
MH_TOOLTIPFAVORITES = "Click to add to favorites"

MH_CATEGORY_ALL = "All"
MH_CATEGORY_RACES = "Races"
MH_CATEGORY_MOUNTS = "Mounts"
MH_CATEGORY_FAVORITES = "Favorites"

MH_TEST = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"
MH_TESTID = "33093"